### ISSUE TITLE
 Additional text encountered after finished reading JSON content

### ISSUE THREAD

**Issue by zortos293** [Elycin/PoolOverSocks5#3]
after few seconds connecting to a pool i get this error

Newtonsoft.Json.JsonReaderException: Additional text encountered after finished reading JSON content: {. Path '', line 2, position 0.
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at PoolOverSocks5.Socket.Miner.ExchangeData() in C:\Users\zorto\Desktop\ZortosMiner\PoolOverSocks5\Socket\Miner.cs:line 115

**Comment by zortos293** [comment]
![image](https://user-images.githubusercontent.com/65777760/131871619-9c1c3f0d-7d49-46b4-903b-1f2990f26763.png)
